select
  r.id as raw_listing_id,
  r.ingestion_id,
  r.source_id,
  r.source_code,
  s.name as source_name,
  r.external_id,
  r.offering_hash,
  r.canonical_url,
  r.title,
  r.transaction_type,
  r.property_type,
  r.city,
  r.state,
  r.neighborhood,
  r.address,
  r.latitude,
  r.longitude,
  r.price_sale,
  r.price_rent,
  r.condo_fee,
  r.iptu,
  r.bedrooms,
  r.bathrooms,
  r.parking_spaces,
  r.area_m2,
  r.description,
  r.broker_name,
  r.published_at,
  r.image_uris,
  r.asset_links,
  r.screenshot_uri,
  r.html_uri,
  r.metadata_uri,
  r.raw_payload,
  r.parsed_at
from {{ source('app', 'raw_listings') }} as r
left join {{ source('app', 'sources') }} as s
  on r.source_id = s.id
