select
  b.id as bronze_listing_id,
  b.ingestion_id,
  b.source_id,
  b.source_code,
  s.name as source_name,
  b.external_id,
  b.offering_hash,
  b.canonical_url,
  b.title,
  b.transaction_type,
  b.property_type,
  b.city,
  b.state,
  b.neighborhood,
  b.address,
  b.latitude,
  b.longitude,
  b.price_sale,
  b.price_rent,
  b.condo_fee,
  b.iptu,
  b.bedrooms,
  b.bathrooms,
  b.parking_spaces,
  b.area_m2,
  b.description,
  b.broker_name,
  b.published_at,
  b.image_uris,
  b.screenshot_uri,
  b.html_uri,
  b.metadata_uri,
  b.raw_payload,
  b.parsed_at
from {{ source('app', 'bronze_listings') }} as b
left join {{ source('app', 'sources') }} as s
  on b.source_id = s.id
