select
  b.offering_hash,
  b.source_code,
  b.source_name,
  b.external_id,
  b.canonical_url,
  b.title,
  b.transaction_type,
  b.property_type,
  b.city,
  b.state,
  b.neighborhood,
  b.address,
  b.latitude,
  b.longitude,
  b.price_sale,
  b.price_rent,
  b.condo_fee,
  b.iptu,
  b.bedrooms,
  b.bathrooms,
  b.parking_spaces,
  b.area_m2,
  b.description,
  b.broker_name,
  b.published_at,
  coalesce(m.image_uris, b.image_uris, '[]'::jsonb) as image_uris,
  coalesce(m.screenshot_uri, b.screenshot_uri) as screenshot_uri,
  coalesce(m.html_uri, b.html_uri) as html_uri,
  coalesce(m.metadata_uri, b.metadata_uri) as metadata_uri,
  b.raw_payload,
  b.parsed_at
from {{ ref('stg_bronze_listings') }} as b
left join {{ ref('int_listing_media') }} as m
  on b.ingestion_id = m.ingestion_id
