select
  offering_hash,
  source_code,
  source_name,
  external_id,
  canonical_url,
  title,
  transaction_type,
  property_type,
  city,
  state,
  neighborhood,
  address,
  latitude,
  longitude,
  geocode_provider,
  geocode_confidence,
  geocode_status,
  geocoded_at,
  coalesce(price_sale, price_rent) as price_display,
  price_sale,
  price_rent,
  bedrooms,
  bathrooms,
  parking_spaces,
  area_m2,
  broker_name,
  published_at,
  listing_created_at,
  listing_updated_at,
  image_uris ->> 0 as primary_image_uri,
  screenshot_uri
from {{ ref('mart_listing_details') }}
