{{ config(materialized='table') }}

-- Deduplicated listings table for the API.
-- One row per offering_hash (unique listing), with temporal tracking from all ingestions.
select
  -- Stable integer ID derived from offering_hash for API compatibility.
  abs(hashtext(d.offering_hash))                         as id,
  d.offering_hash,
  d.source_id,
  d.source_code,
  d.source_name,
  d.external_id,
  d.canonical_url,
  d.title,
  d.transaction_type,
  d.property_type,
  d.city,
  d.state,
  d.neighborhood,
  d.address,
  d.latitude,
  d.longitude,
  d.geocode_provider,
  d.geocode_query,
  d.geocode_confidence,
  d.geocode_status,
  d.geocode_payload,
  d.geocoded_at,
  d.price_sale,
  d.price_rent,
  d.condo_fee,
  d.iptu,
  d.bedrooms,
  d.bathrooms,
  d.parking_spaces,
  d.area_m2,
  d.description,
  d.broker_name,
  d.published_at,
  d.listing_created_at,
  d.listing_updated_at,
  coalesce(d.raw_image_uris, '[]'::jsonb)                as image_uris,
  d.has_asset_links,
  d.screenshot_uri,
  d.first_seen_at,
  d.last_seen_at,
  d.last_scraped_at,
  d.is_active
from {{ ref('int_listings_enriched') }} as d
